### ISSUE TITLE
Does this dep work?

### ISSUE THREAD

**Issue by benonymus** [ExHammer/hammer-backend-ecto#11]
Hey,

I am wondering if this dep is working or not considering the open issue about the migration.
Is there a migration template somewhere if that is the only thing that is missing?

EDIT: 
I checked the code, I see it does not work for the time being.

Is there a timeline on this?

Thank you

**Comment by epinault** [comment]
sorry just noticed this. I don t have a timeline as I inherited it and not quite sure what the plan was. but happy to get more help

**Comment by benonymus** [comment]
Hey,
This is not urgent or important for me anymore, so no worries!
Thanks
